// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: locations.proto

package org.deepak.grpc.protoFiles;

public final class Locations {
  private Locations() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface locationIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:locationId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code locationId}
   */
  public  static final class locationId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:locationId)
      locationIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use locationId.newBuilder() to construct.
    private locationId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private locationId() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private locationId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deepak.grpc.protoFiles.Locations.internal_static_locationId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deepak.grpc.protoFiles.Locations.internal_static_locationId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.deepak.grpc.protoFiles.Locations.locationId.class, org.deepak.grpc.protoFiles.Locations.locationId.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.deepak.grpc.protoFiles.Locations.locationId)) {
        return super.equals(obj);
      }
      org.deepak.grpc.protoFiles.Locations.locationId other = (org.deepak.grpc.protoFiles.Locations.locationId) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.deepak.grpc.protoFiles.Locations.locationId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code locationId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:locationId)
        org.deepak.grpc.protoFiles.Locations.locationIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_locationId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_locationId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.deepak.grpc.protoFiles.Locations.locationId.class, org.deepak.grpc.protoFiles.Locations.locationId.Builder.class);
      }

      // Construct using org.deepak.grpc.protoFiles.Locations.locationId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_locationId_descriptor;
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.locationId getDefaultInstanceForType() {
        return org.deepak.grpc.protoFiles.Locations.locationId.getDefaultInstance();
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.locationId build() {
        org.deepak.grpc.protoFiles.Locations.locationId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.locationId buildPartial() {
        org.deepak.grpc.protoFiles.Locations.locationId result = new org.deepak.grpc.protoFiles.Locations.locationId(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deepak.grpc.protoFiles.Locations.locationId) {
          return mergeFrom((org.deepak.grpc.protoFiles.Locations.locationId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.deepak.grpc.protoFiles.Locations.locationId other) {
        if (other == org.deepak.grpc.protoFiles.Locations.locationId.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.deepak.grpc.protoFiles.Locations.locationId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.deepak.grpc.protoFiles.Locations.locationId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:locationId)
    }

    // @@protoc_insertion_point(class_scope:locationId)
    private static final org.deepak.grpc.protoFiles.Locations.locationId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.deepak.grpc.protoFiles.Locations.locationId();
    }

    public static org.deepak.grpc.protoFiles.Locations.locationId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<locationId>
        PARSER = new com.google.protobuf.AbstractParser<locationId>() {
      @java.lang.Override
      public locationId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new locationId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<locationId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<locationId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.deepak.grpc.protoFiles.Locations.locationId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface locationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string locationName = 1;</code>
     */
    java.lang.String getLocationName();
    /**
     * <code>string locationName = 1;</code>
     */
    com.google.protobuf.ByteString
        getLocationNameBytes();

    /**
     * <code>int32 locationLongitude = 2;</code>
     */
    int getLocationLongitude();

    /**
     * <code>int32 locationLatitude = 3;</code>
     */
    int getLocationLatitude();

    /**
     * <code>int32 locationActive = 4;</code>
     */
    int getLocationActive();
  }
  /**
   * Protobuf type {@code location}
   */
  public  static final class location extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:location)
      locationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use location.newBuilder() to construct.
    private location(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private location() {
      locationName_ = "";
      locationLongitude_ = 0;
      locationLatitude_ = 0;
      locationActive_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              locationName_ = s;
              break;
            }
            case 16: {

              locationLongitude_ = input.readInt32();
              break;
            }
            case 24: {

              locationLatitude_ = input.readInt32();
              break;
            }
            case 32: {

              locationActive_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deepak.grpc.protoFiles.Locations.internal_static_location_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deepak.grpc.protoFiles.Locations.internal_static_location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.deepak.grpc.protoFiles.Locations.location.class, org.deepak.grpc.protoFiles.Locations.location.Builder.class);
    }

    public static final int LOCATIONNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object locationName_;
    /**
     * <code>string locationName = 1;</code>
     */
    public java.lang.String getLocationName() {
      java.lang.Object ref = locationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locationName_ = s;
        return s;
      }
    }
    /**
     * <code>string locationName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLocationNameBytes() {
      java.lang.Object ref = locationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATIONLONGITUDE_FIELD_NUMBER = 2;
    private int locationLongitude_;
    /**
     * <code>int32 locationLongitude = 2;</code>
     */
    public int getLocationLongitude() {
      return locationLongitude_;
    }

    public static final int LOCATIONLATITUDE_FIELD_NUMBER = 3;
    private int locationLatitude_;
    /**
     * <code>int32 locationLatitude = 3;</code>
     */
    public int getLocationLatitude() {
      return locationLatitude_;
    }

    public static final int LOCATIONACTIVE_FIELD_NUMBER = 4;
    private int locationActive_;
    /**
     * <code>int32 locationActive = 4;</code>
     */
    public int getLocationActive() {
      return locationActive_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLocationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, locationName_);
      }
      if (locationLongitude_ != 0) {
        output.writeInt32(2, locationLongitude_);
      }
      if (locationLatitude_ != 0) {
        output.writeInt32(3, locationLatitude_);
      }
      if (locationActive_ != 0) {
        output.writeInt32(4, locationActive_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLocationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, locationName_);
      }
      if (locationLongitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, locationLongitude_);
      }
      if (locationLatitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, locationLatitude_);
      }
      if (locationActive_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, locationActive_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.deepak.grpc.protoFiles.Locations.location)) {
        return super.equals(obj);
      }
      org.deepak.grpc.protoFiles.Locations.location other = (org.deepak.grpc.protoFiles.Locations.location) obj;

      boolean result = true;
      result = result && getLocationName()
          .equals(other.getLocationName());
      result = result && (getLocationLongitude()
          == other.getLocationLongitude());
      result = result && (getLocationLatitude()
          == other.getLocationLatitude());
      result = result && (getLocationActive()
          == other.getLocationActive());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLocationName().hashCode();
      hash = (37 * hash) + LOCATIONLONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLocationLongitude();
      hash = (37 * hash) + LOCATIONLATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLocationLatitude();
      hash = (37 * hash) + LOCATIONACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + getLocationActive();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.deepak.grpc.protoFiles.Locations.location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:location)
        org.deepak.grpc.protoFiles.Locations.locationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_location_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.deepak.grpc.protoFiles.Locations.location.class, org.deepak.grpc.protoFiles.Locations.location.Builder.class);
      }

      // Construct using org.deepak.grpc.protoFiles.Locations.location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        locationName_ = "";

        locationLongitude_ = 0;

        locationLatitude_ = 0;

        locationActive_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_location_descriptor;
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.location getDefaultInstanceForType() {
        return org.deepak.grpc.protoFiles.Locations.location.getDefaultInstance();
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.location build() {
        org.deepak.grpc.protoFiles.Locations.location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.location buildPartial() {
        org.deepak.grpc.protoFiles.Locations.location result = new org.deepak.grpc.protoFiles.Locations.location(this);
        result.locationName_ = locationName_;
        result.locationLongitude_ = locationLongitude_;
        result.locationLatitude_ = locationLatitude_;
        result.locationActive_ = locationActive_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deepak.grpc.protoFiles.Locations.location) {
          return mergeFrom((org.deepak.grpc.protoFiles.Locations.location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.deepak.grpc.protoFiles.Locations.location other) {
        if (other == org.deepak.grpc.protoFiles.Locations.location.getDefaultInstance()) return this;
        if (!other.getLocationName().isEmpty()) {
          locationName_ = other.locationName_;
          onChanged();
        }
        if (other.getLocationLongitude() != 0) {
          setLocationLongitude(other.getLocationLongitude());
        }
        if (other.getLocationLatitude() != 0) {
          setLocationLatitude(other.getLocationLatitude());
        }
        if (other.getLocationActive() != 0) {
          setLocationActive(other.getLocationActive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.deepak.grpc.protoFiles.Locations.location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.deepak.grpc.protoFiles.Locations.location) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object locationName_ = "";
      /**
       * <code>string locationName = 1;</code>
       */
      public java.lang.String getLocationName() {
        java.lang.Object ref = locationName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          locationName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string locationName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLocationNameBytes() {
        java.lang.Object ref = locationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string locationName = 1;</code>
       */
      public Builder setLocationName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        locationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string locationName = 1;</code>
       */
      public Builder clearLocationName() {
        
        locationName_ = getDefaultInstance().getLocationName();
        onChanged();
        return this;
      }
      /**
       * <code>string locationName = 1;</code>
       */
      public Builder setLocationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        locationName_ = value;
        onChanged();
        return this;
      }

      private int locationLongitude_ ;
      /**
       * <code>int32 locationLongitude = 2;</code>
       */
      public int getLocationLongitude() {
        return locationLongitude_;
      }
      /**
       * <code>int32 locationLongitude = 2;</code>
       */
      public Builder setLocationLongitude(int value) {
        
        locationLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locationLongitude = 2;</code>
       */
      public Builder clearLocationLongitude() {
        
        locationLongitude_ = 0;
        onChanged();
        return this;
      }

      private int locationLatitude_ ;
      /**
       * <code>int32 locationLatitude = 3;</code>
       */
      public int getLocationLatitude() {
        return locationLatitude_;
      }
      /**
       * <code>int32 locationLatitude = 3;</code>
       */
      public Builder setLocationLatitude(int value) {
        
        locationLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locationLatitude = 3;</code>
       */
      public Builder clearLocationLatitude() {
        
        locationLatitude_ = 0;
        onChanged();
        return this;
      }

      private int locationActive_ ;
      /**
       * <code>int32 locationActive = 4;</code>
       */
      public int getLocationActive() {
        return locationActive_;
      }
      /**
       * <code>int32 locationActive = 4;</code>
       */
      public Builder setLocationActive(int value) {
        
        locationActive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locationActive = 4;</code>
       */
      public Builder clearLocationActive() {
        
        locationActive_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:location)
    }

    // @@protoc_insertion_point(class_scope:location)
    private static final org.deepak.grpc.protoFiles.Locations.location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.deepak.grpc.protoFiles.Locations.location();
    }

    public static org.deepak.grpc.protoFiles.Locations.location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<location>
        PARSER = new com.google.protobuf.AbstractParser<location>() {
      @java.lang.Override
      public location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new location(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<location> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.deepak.grpc.protoFiles.Locations.location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface locationUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:locationUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 locationId = 1;</code>
     */
    int getLocationId();

    /**
     * <code>string locationName = 2;</code>
     */
    java.lang.String getLocationName();
    /**
     * <code>string locationName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLocationNameBytes();

    /**
     * <code>int32 locationLongitude = 3;</code>
     */
    int getLocationLongitude();

    /**
     * <code>int32 locationLatitude = 4;</code>
     */
    int getLocationLatitude();

    /**
     * <code>int32 locationActive = 5;</code>
     */
    int getLocationActive();
  }
  /**
   * Protobuf type {@code locationUpdate}
   */
  public  static final class locationUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:locationUpdate)
      locationUpdateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use locationUpdate.newBuilder() to construct.
    private locationUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private locationUpdate() {
      locationId_ = 0;
      locationName_ = "";
      locationLongitude_ = 0;
      locationLatitude_ = 0;
      locationActive_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private locationUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              locationId_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              locationName_ = s;
              break;
            }
            case 24: {

              locationLongitude_ = input.readInt32();
              break;
            }
            case 32: {

              locationLatitude_ = input.readInt32();
              break;
            }
            case 40: {

              locationActive_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deepak.grpc.protoFiles.Locations.internal_static_locationUpdate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deepak.grpc.protoFiles.Locations.internal_static_locationUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.deepak.grpc.protoFiles.Locations.locationUpdate.class, org.deepak.grpc.protoFiles.Locations.locationUpdate.Builder.class);
    }

    public static final int LOCATIONID_FIELD_NUMBER = 1;
    private int locationId_;
    /**
     * <code>int32 locationId = 1;</code>
     */
    public int getLocationId() {
      return locationId_;
    }

    public static final int LOCATIONNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object locationName_;
    /**
     * <code>string locationName = 2;</code>
     */
    public java.lang.String getLocationName() {
      java.lang.Object ref = locationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locationName_ = s;
        return s;
      }
    }
    /**
     * <code>string locationName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLocationNameBytes() {
      java.lang.Object ref = locationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATIONLONGITUDE_FIELD_NUMBER = 3;
    private int locationLongitude_;
    /**
     * <code>int32 locationLongitude = 3;</code>
     */
    public int getLocationLongitude() {
      return locationLongitude_;
    }

    public static final int LOCATIONLATITUDE_FIELD_NUMBER = 4;
    private int locationLatitude_;
    /**
     * <code>int32 locationLatitude = 4;</code>
     */
    public int getLocationLatitude() {
      return locationLatitude_;
    }

    public static final int LOCATIONACTIVE_FIELD_NUMBER = 5;
    private int locationActive_;
    /**
     * <code>int32 locationActive = 5;</code>
     */
    public int getLocationActive() {
      return locationActive_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (locationId_ != 0) {
        output.writeInt32(1, locationId_);
      }
      if (!getLocationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, locationName_);
      }
      if (locationLongitude_ != 0) {
        output.writeInt32(3, locationLongitude_);
      }
      if (locationLatitude_ != 0) {
        output.writeInt32(4, locationLatitude_);
      }
      if (locationActive_ != 0) {
        output.writeInt32(5, locationActive_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (locationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, locationId_);
      }
      if (!getLocationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, locationName_);
      }
      if (locationLongitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, locationLongitude_);
      }
      if (locationLatitude_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, locationLatitude_);
      }
      if (locationActive_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, locationActive_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.deepak.grpc.protoFiles.Locations.locationUpdate)) {
        return super.equals(obj);
      }
      org.deepak.grpc.protoFiles.Locations.locationUpdate other = (org.deepak.grpc.protoFiles.Locations.locationUpdate) obj;

      boolean result = true;
      result = result && (getLocationId()
          == other.getLocationId());
      result = result && getLocationName()
          .equals(other.getLocationName());
      result = result && (getLocationLongitude()
          == other.getLocationLongitude());
      result = result && (getLocationLatitude()
          == other.getLocationLatitude());
      result = result && (getLocationActive()
          == other.getLocationActive());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCATIONID_FIELD_NUMBER;
      hash = (53 * hash) + getLocationId();
      hash = (37 * hash) + LOCATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLocationName().hashCode();
      hash = (37 * hash) + LOCATIONLONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLocationLongitude();
      hash = (37 * hash) + LOCATIONLATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + getLocationLatitude();
      hash = (37 * hash) + LOCATIONACTIVE_FIELD_NUMBER;
      hash = (53 * hash) + getLocationActive();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.locationUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.deepak.grpc.protoFiles.Locations.locationUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code locationUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:locationUpdate)
        org.deepak.grpc.protoFiles.Locations.locationUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_locationUpdate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_locationUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.deepak.grpc.protoFiles.Locations.locationUpdate.class, org.deepak.grpc.protoFiles.Locations.locationUpdate.Builder.class);
      }

      // Construct using org.deepak.grpc.protoFiles.Locations.locationUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        locationId_ = 0;

        locationName_ = "";

        locationLongitude_ = 0;

        locationLatitude_ = 0;

        locationActive_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_locationUpdate_descriptor;
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.locationUpdate getDefaultInstanceForType() {
        return org.deepak.grpc.protoFiles.Locations.locationUpdate.getDefaultInstance();
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.locationUpdate build() {
        org.deepak.grpc.protoFiles.Locations.locationUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.locationUpdate buildPartial() {
        org.deepak.grpc.protoFiles.Locations.locationUpdate result = new org.deepak.grpc.protoFiles.Locations.locationUpdate(this);
        result.locationId_ = locationId_;
        result.locationName_ = locationName_;
        result.locationLongitude_ = locationLongitude_;
        result.locationLatitude_ = locationLatitude_;
        result.locationActive_ = locationActive_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deepak.grpc.protoFiles.Locations.locationUpdate) {
          return mergeFrom((org.deepak.grpc.protoFiles.Locations.locationUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.deepak.grpc.protoFiles.Locations.locationUpdate other) {
        if (other == org.deepak.grpc.protoFiles.Locations.locationUpdate.getDefaultInstance()) return this;
        if (other.getLocationId() != 0) {
          setLocationId(other.getLocationId());
        }
        if (!other.getLocationName().isEmpty()) {
          locationName_ = other.locationName_;
          onChanged();
        }
        if (other.getLocationLongitude() != 0) {
          setLocationLongitude(other.getLocationLongitude());
        }
        if (other.getLocationLatitude() != 0) {
          setLocationLatitude(other.getLocationLatitude());
        }
        if (other.getLocationActive() != 0) {
          setLocationActive(other.getLocationActive());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.deepak.grpc.protoFiles.Locations.locationUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.deepak.grpc.protoFiles.Locations.locationUpdate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int locationId_ ;
      /**
       * <code>int32 locationId = 1;</code>
       */
      public int getLocationId() {
        return locationId_;
      }
      /**
       * <code>int32 locationId = 1;</code>
       */
      public Builder setLocationId(int value) {
        
        locationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locationId = 1;</code>
       */
      public Builder clearLocationId() {
        
        locationId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object locationName_ = "";
      /**
       * <code>string locationName = 2;</code>
       */
      public java.lang.String getLocationName() {
        java.lang.Object ref = locationName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          locationName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string locationName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLocationNameBytes() {
        java.lang.Object ref = locationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string locationName = 2;</code>
       */
      public Builder setLocationName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        locationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string locationName = 2;</code>
       */
      public Builder clearLocationName() {
        
        locationName_ = getDefaultInstance().getLocationName();
        onChanged();
        return this;
      }
      /**
       * <code>string locationName = 2;</code>
       */
      public Builder setLocationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        locationName_ = value;
        onChanged();
        return this;
      }

      private int locationLongitude_ ;
      /**
       * <code>int32 locationLongitude = 3;</code>
       */
      public int getLocationLongitude() {
        return locationLongitude_;
      }
      /**
       * <code>int32 locationLongitude = 3;</code>
       */
      public Builder setLocationLongitude(int value) {
        
        locationLongitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locationLongitude = 3;</code>
       */
      public Builder clearLocationLongitude() {
        
        locationLongitude_ = 0;
        onChanged();
        return this;
      }

      private int locationLatitude_ ;
      /**
       * <code>int32 locationLatitude = 4;</code>
       */
      public int getLocationLatitude() {
        return locationLatitude_;
      }
      /**
       * <code>int32 locationLatitude = 4;</code>
       */
      public Builder setLocationLatitude(int value) {
        
        locationLatitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locationLatitude = 4;</code>
       */
      public Builder clearLocationLatitude() {
        
        locationLatitude_ = 0;
        onChanged();
        return this;
      }

      private int locationActive_ ;
      /**
       * <code>int32 locationActive = 5;</code>
       */
      public int getLocationActive() {
        return locationActive_;
      }
      /**
       * <code>int32 locationActive = 5;</code>
       */
      public Builder setLocationActive(int value) {
        
        locationActive_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 locationActive = 5;</code>
       */
      public Builder clearLocationActive() {
        
        locationActive_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:locationUpdate)
    }

    // @@protoc_insertion_point(class_scope:locationUpdate)
    private static final org.deepak.grpc.protoFiles.Locations.locationUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.deepak.grpc.protoFiles.Locations.locationUpdate();
    }

    public static org.deepak.grpc.protoFiles.Locations.locationUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<locationUpdate>
        PARSER = new com.google.protobuf.AbstractParser<locationUpdate>() {
      @java.lang.Override
      public locationUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new locationUpdate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<locationUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<locationUpdate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.deepak.grpc.protoFiles.Locations.locationUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface APIResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:APIResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string responseMessage = 1;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <code>string responseMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();

    /**
     * <code>int32 messageCode = 2;</code>
     */
    int getMessageCode();
  }
  /**
   * Protobuf type {@code APIResponse}
   */
  public  static final class APIResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:APIResponse)
      APIResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use APIResponse.newBuilder() to construct.
    private APIResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private APIResponse() {
      responseMessage_ = "";
      messageCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private APIResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            case 16: {

              messageCode_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.deepak.grpc.protoFiles.Locations.internal_static_APIResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.deepak.grpc.protoFiles.Locations.internal_static_APIResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.deepak.grpc.protoFiles.Locations.APIResponse.class, org.deepak.grpc.protoFiles.Locations.APIResponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseMessage_;
    /**
     * <code>string responseMessage = 1;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string responseMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGECODE_FIELD_NUMBER = 2;
    private int messageCode_;
    /**
     * <code>int32 messageCode = 2;</code>
     */
    public int getMessageCode() {
      return messageCode_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseMessage_);
      }
      if (messageCode_ != 0) {
        output.writeInt32(2, messageCode_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseMessage_);
      }
      if (messageCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.deepak.grpc.protoFiles.Locations.APIResponse)) {
        return super.equals(obj);
      }
      org.deepak.grpc.protoFiles.Locations.APIResponse other = (org.deepak.grpc.protoFiles.Locations.APIResponse) obj;

      boolean result = true;
      result = result && getResponseMessage()
          .equals(other.getResponseMessage());
      result = result && (getMessageCode()
          == other.getMessageCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (37 * hash) + MESSAGECODE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.deepak.grpc.protoFiles.Locations.APIResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.deepak.grpc.protoFiles.Locations.APIResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code APIResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:APIResponse)
        org.deepak.grpc.protoFiles.Locations.APIResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_APIResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.deepak.grpc.protoFiles.Locations.APIResponse.class, org.deepak.grpc.protoFiles.Locations.APIResponse.Builder.class);
      }

      // Construct using org.deepak.grpc.protoFiles.Locations.APIResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseMessage_ = "";

        messageCode_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.deepak.grpc.protoFiles.Locations.internal_static_APIResponse_descriptor;
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.APIResponse getDefaultInstanceForType() {
        return org.deepak.grpc.protoFiles.Locations.APIResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.APIResponse build() {
        org.deepak.grpc.protoFiles.Locations.APIResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.deepak.grpc.protoFiles.Locations.APIResponse buildPartial() {
        org.deepak.grpc.protoFiles.Locations.APIResponse result = new org.deepak.grpc.protoFiles.Locations.APIResponse(this);
        result.responseMessage_ = responseMessage_;
        result.messageCode_ = messageCode_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.deepak.grpc.protoFiles.Locations.APIResponse) {
          return mergeFrom((org.deepak.grpc.protoFiles.Locations.APIResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.deepak.grpc.protoFiles.Locations.APIResponse other) {
        if (other == org.deepak.grpc.protoFiles.Locations.APIResponse.getDefaultInstance()) return this;
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        if (other.getMessageCode() != 0) {
          setMessageCode(other.getMessageCode());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.deepak.grpc.protoFiles.Locations.APIResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.deepak.grpc.protoFiles.Locations.APIResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <code>string responseMessage = 1;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }

      private int messageCode_ ;
      /**
       * <code>int32 messageCode = 2;</code>
       */
      public int getMessageCode() {
        return messageCode_;
      }
      /**
       * <code>int32 messageCode = 2;</code>
       */
      public Builder setMessageCode(int value) {
        
        messageCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageCode = 2;</code>
       */
      public Builder clearMessageCode() {
        
        messageCode_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:APIResponse)
    }

    // @@protoc_insertion_point(class_scope:APIResponse)
    private static final org.deepak.grpc.protoFiles.Locations.APIResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.deepak.grpc.protoFiles.Locations.APIResponse();
    }

    public static org.deepak.grpc.protoFiles.Locations.APIResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<APIResponse>
        PARSER = new com.google.protobuf.AbstractParser<APIResponse>() {
      @java.lang.Override
      public APIResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new APIResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<APIResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<APIResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.deepak.grpc.protoFiles.Locations.APIResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_locationId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_locationId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_location_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_locationUpdate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_locationUpdate_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_APIResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_APIResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017locations.proto\"\030\n\nlocationId\022\n\n\002id\030\001 " +
      "\001(\005\"m\n\010location\022\024\n\014locationName\030\001 \001(\t\022\031\n" +
      "\021locationLongitude\030\002 \001(\005\022\030\n\020locationLati" +
      "tude\030\003 \001(\005\022\026\n\016locationActive\030\004 \001(\005\"\207\001\n\016l" +
      "ocationUpdate\022\022\n\nlocationId\030\001 \001(\005\022\024\n\014loc" +
      "ationName\030\002 \001(\t\022\031\n\021locationLongitude\030\003 \001" +
      "(\005\022\030\n\020locationLatitude\030\004 \001(\005\022\026\n\016location" +
      "Active\030\005 \001(\005\";\n\013APIResponse\022\027\n\017responseM" +
      "essage\030\001 \001(\t\022\023\n\013messageCode\030\002 \001(\0052\273\001\n\tlo" +
      "cations\022(\n\013getLocation\022\013.locationId\032\014.AP" +
      "IResponse\022&\n\013addLocation\022\t.location\032\014.AP" +
      "IResponse\022/\n\016updateLocation\022\017.locationUp" +
      "date\032\014.APIResponse\022+\n\016deleteLocation\022\013.l" +
      "ocationId\032\014.APIResponseB\034\n\032org.deepak.gr" +
      "pc.protoFilesb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_locationId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_locationId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_locationId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_location_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_location_descriptor,
        new java.lang.String[] { "LocationName", "LocationLongitude", "LocationLatitude", "LocationActive", });
    internal_static_locationUpdate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_locationUpdate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_locationUpdate_descriptor,
        new java.lang.String[] { "LocationId", "LocationName", "LocationLongitude", "LocationLatitude", "LocationActive", });
    internal_static_APIResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_APIResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_APIResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "MessageCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
